#
# FROM golang:1.20

# syntax=docker/dockerfile:1

FROM golang:1.20-alpine

WORKDIR /app

# COPY go.mod ./
# COPY go.sum ./
# RUN go mod download

# COPY ./products /app/products
# COPY ./DB /app/DB
# COPY ./utils /app/utils

COPY . .


RUN go build -o /products cmd/products/main.go

EXPOSE 4001

CMD [ "/products" ]