#
# FROM golang:1.20

# syntax=docker/dockerfile:1

FROM golang:1.20-alpine

WORKDIR /app

# COPY go.mod ./
# COPY go.sum ./
# RUN go mod download

# COPY ./src/products /app/src/products
# COPY ./DB /app/DB
# COPY ./utils /app/utils
# COPY ./cmd/products /app/cmd/products

COPY . .


RUN go build -o /users cmd/users/main.go

EXPOSE 4002

CMD [ "/users" ]